name: Export Marp Presentation

on:
    push:
        branches:
            - main

jobs:
    export:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PAT_TOKEN }}

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '19'

            - name: Install dependencies
              run: npm ci

            - name: Export Marp presentation to PDF and HTML
              run: npm run export
            - name: Create Git tag
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git tag "v${{ github.run_number }}"
                  git push origin "v${{ github.run_number }}"

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      Curso_Fotografía_digital.pdf
                      Curso_Fotografía_digital.html
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
